server.port=8085

spring.datasource.url=jdbc:mysql://localhost:3306/student1_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
spring.datasource.username=root
spring.datasource.password=hoan123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

app.jwt.secret=SinhVienCNTT2026SecretKeyForJWTTokenGenerationMustBeLongEnough256Bits
app.jwt.expiration-ms=86400000

app.crawled-data-path=D:\AndroidProject\CDTN\CDTN\crawled_data

app.resend.api-key=re_34pau2R4_9fXu5vcBo6MzBWNaXJpHLcC6
app.resend.from=noreply@qlhtt.io.vn
app.resend.from-name=SV CNTT
